name: "connect-db"
services:
  pgvector:
    image: pgvector/pgvector:pg17
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passpass
    volumes:
      - ./sql/common.sql:/docker-entrypoint-initdb.d/common.sql
      - ./dontsave/pgdata:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"
  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
