const DEFAULT_QUERY_EMBEDDINGS_QUEUE_NAME = "query-embeddings"

export const QUERY_EMBEDDINGS_QUEUE_NAME =
  process.env.QUERY_EMBEDDINGS_QUEUE_NAME ?? DEFAULT_QUERY_EMBEDDINGS_QUEUE_NAME
export const QUERY_EMBEDDINGS_JOB_NAME = "embed-query"
