import { EXTRACTION_AGENT_SESSION_STATUS_CHANGED_CHANNEL_DTO } from "@caseai-connect/api-contracts"

export const EXTRACTION_AGENT_SESSION_STATUS_CHANGED_CHANNEL =
  EXTRACTION_AGENT_SESSION_STATUS_CHANGED_CHANNEL_DTO
