const DEFAULT_DOCLING_CRAWLING_QUEUE_NAME = "docling-crawling"

export const DOCLING_CRAWLING_QUEUE_NAME =
  process.env.DOCLING_CRAWLING_QUEUE_NAME ?? DEFAULT_DOCLING_CRAWLING_QUEUE_NAME
export const DOCLING_CRAWLING_JOB_NAME = "crawl-url-docling"
