const DEFAULT_WEB_SOURCE_EMBEDDINGS_QUEUE_NAME = "web-source-embeddings"

export const WEB_SOURCE_EMBEDDINGS_QUEUE_NAME =
  process.env.WEB_SOURCE_EMBEDDINGS_QUEUE_NAME ?? DEFAULT_WEB_SOURCE_EMBEDDINGS_QUEUE_NAME
export const WEB_SOURCE_EMBEDDINGS_JOB_NAME = "create-web-source-embeddings"
